### ISSUE TITLE
GLIBC_2.33 not found

### ISSUE THREAD

**Issue by olesya-wo** [hockyy/miteiru#45]
Miteiru v2.0.0 from .deb installer
OS - Linux Mint 20.2 Uma
I got an error:
```
> miteiru
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/miteiru/resources/app.asar.unpacked/node_modules/classic-level/build/Release/classic_level.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/opt/miteiru/resources/app.asar/node_modules/classic-level/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/opt/miteiru/resources/app.asar/node_modules/classic-level/binding.js:1:43)
```
It fixed by
```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install -y g++-11
```
But I don't know how to fix the next one:
```
> miteiru
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/miteiru/resources/app.asar.unpacked/node_modules/classic-level/build/Release/classic_level.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/opt/miteiru/resources/app.asar/node_modules/classic-level/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/opt/miteiru/resources/app.asar/node_modules/classic-level/binding.js:1:43)
```

**Comment by hockyy** [comment]
```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install libstdc++6-7-dbg
```

**Comment by hockyy** [comment]
@olesya-wo have tried installing the libstdc++? Im not sure whether it will work but you can try building your own for your OS if it still fails

**Comment by hockyy** [comment]
I think I found the issue, linux mint doesnt have `build-essential` by default

**Comment by olesya-wo** [comment]
```
> sudo apt-get install build-essential
build-essential is already the newest version (12.8ubuntu1.1).
```

`sudo apt-get install libstdc++6` also doesn't help

**Comment by hockyy** [comment]
im downloading the OS @olesya-wo give me 1 hour

**Comment by hockyy** [comment]
![image](https://github.com/hockyy/miteiru/assets/19528709/113aba3a-1f72-4216-a2cf-1f2fa626c48a)

Okay, I'm able to reproduce the error.

**Comment by hockyy** [comment]
@olesya-wo Linux Kernel version issue, I prebuild the binary for 20.04 based Ubuntu https://github.com/hockyy/miteiru/releases/download/v2.0.0/miteiru_2.0.0_amd64-Linux-20.04.deb

**Comment by hockyy** [comment]
Happy immersing!
